(function(){
  'use strict';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const defs=window.STARRO_CMS_DEFS||{};
  let activePageKey='index';
  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function getCfg(){try{return cfg}catch(e){return window.StarroConfig?.all?.()||{}}}
  function ensureUi(){const c=getCfg();c.ui=c.ui||{};c.ui.pages=c.ui.pages||{};return c}
  function pageState(key){const d=defs[key],c=ensureUi().ui.pages[key]||{};const blocks=Array.isArray(c.blocks)?c.blocks:d.blocks.map(b=>({key:b.key,visible:true,title:b.label}));return {enabled:c.enabled!==false,title:c.title??d.title,subtitle:c.subtitle??d.subtitle,blocks,overrides:Array.isArray(c.overrides)?c.overrides:[]}}
  function ensurePanel(key){const panels=$('#panels');if(!panels)return null;let p=$(`[data-panel="${key}"]`,panels);if(!p){p=document.createElement('section');p.className='panel';p.dataset.panel=key;panels.appendChild(p)}return p}
  function insertNavButton(key,html,afterKey){const nav=$('#sideNav');if(!nav||$(`[data-open="${key}"]`,nav))return;const b=document.createElement('button');b.dataset.open=key;b.innerHTML=html;const after=$(`[data-open="${afterKey}"]`,nav);if(after)after.insertAdjacentElement('afterend',b);else nav.appendChild(b)}
  function insertFeatureRow(key,title,summary,afterKey){const table=$('#featureTable');if(!table||$(`[data-cms-feature="${key}"]`,table))return;const row=document.createElement('div');row.className='feature-row';row.dataset.cmsFeature=key;row.innerHTML=`<div><div class="feature-title">${title}</div><div class="feature-summary">${summary}</div></div><span class="pill">完整後台</span><button class="btn" data-open="${key}">查看</button>`;const afterBtn=$(`[data-open="${afterKey}"]`,table);const after=afterBtn?.closest('.feature-row');if(after)after.insertAdjacentElement('afterend',row);else table.appendChild(row)}
  function blockRowsHtml(key,state){const d=defs[key],map=new Map(d.blocks.map(b=>[b.key,b]));return state.blocks.map((b,i)=>{const bd=map.get(b.key)||{label:b.key};return `<div class="cms-block-row" draggable="true" data-block-key="${esc(b.key)}"><div class="cms-drag" title="拖曳排序">⋮⋮</div><label class="switch-inline"><input class="cms-block-visible" type="checkbox" ${b.visible!==false?'checked':''}> 顯示</label><div class="cms-block-label">${esc(bd.label)}</div><input class="cms-block-title" type="text" value="${esc(b.title??bd.label)}" placeholder="顯示標題"><div class="cms-block-actions"><button class="btn" type="button" data-cms-up>↑</button><button class="btn" type="button" data-cms-down>↓</button></div></div>`}).join('')}
  function renderPageEditor(){
    const panel=ensurePanel('fullCms');if(!panel)return;const state=pageState(activePageKey),d=defs[activePageKey];
    panel.innerHTML=`<div class="panel-head"><div><h2>🧩 全部頁面管理</h2><div class="muted">所有前台頁面都可從這裡管理：頁面啟用、標題、副標題、區塊顯示、區塊排序、區塊標題，以及進階 DOM 覆寫。</div></div><div class="spacer"></div><a class="btn ghost" href="${d.file}" target="_blank">開啟前台</a></div>
    <div class="cms-admin-tabs">${Object.values(defs).map(x=>`<button class="btn ${x.key===activePageKey?'active':''}" type="button" data-cms-page="${x.key}">${x.icon} ${x.label}</button>`).join('')}</div>
    <div class="cms-page-editor">
      <div class="section"><div class="cms-page-head-grid"><div class="cms-page-toggle"><label class="switch-inline"><input id="cmsPageEnabled" type="checkbox" ${state.enabled?'checked':''}> 啟用此頁</label><div class="mini-help">關閉後直接開網址時會顯示「此頁暫停使用」。導覽列是否出現則由「主頁導覽設定」控制。</div></div><div><div class="inline-fields"><label class="field"><span>頁面 H1 標題</span><input id="cmsPageTitle" value="${esc(state.title)}"></label><label class="field"><span>副標題 / 說明</span><input id="cmsPageSubtitle" value="${esc(state.subtitle)}"></label></div></div></div></div>
      <div class="section"><div class="panel-head slim"><div><h2 style="font-size:18px">頁面區塊</h2><div class="muted">直接拖曳或按 ↑↓ 改順序；可隱藏區塊與覆寫區塊標題。</div></div><div class="spacer"></div><button class="btn ghost" type="button" id="cmsResetBlocks">恢復本頁預設</button></div><div class="cms-block-list" id="cmsBlockList">${blockRowsHtml(activePageKey,state)}</div></div>
      <div class="section"><h3>🧰 進階 DOM 覆寫</h3><div class="cms-override-help">這是「完全後台化」的通用工具。可用 CSS selector 修改前台任何元素。JSON 每筆格式：<br><code>{"selector":"#某元素","type":"text","value":"新文字","enabled":true}</code><br>支援 type：text、html、value、placeholder、href、src、hidden、style、classAdd。若不需要可保持空陣列。</div><textarea id="cmsOverridesJson" class="cms-json">${esc(JSON.stringify(state.overrides,null,2))}</textarea></div>
      <div class="section"><div class="home-actions"><button class="btn primary" type="button" id="cmsSavePage">💾 儲存本頁設定</button><button class="btn blue" type="button" id="cmsSaveAllPages">💾 儲存全部到雲端</button><button class="btn ghost" type="button" id="cmsExportPage">⬇️ 匯出本頁 JSON</button></div></div>
    </div>`;
  }
  function collectPageState(){const list=$('#cmsBlockList');let overrides=[];try{overrides=JSON.parse($('#cmsOverridesJson')?.value||'[]');if(!Array.isArray(overrides))throw new Error('必須是 JSON 陣列')}catch(e){throw new Error('進階 DOM 覆寫 JSON 格式錯誤：'+e.message)}return {enabled:$('#cmsPageEnabled')?.checked!==false,title:$('#cmsPageTitle')?.value||defs[activePageKey].title,subtitle:$('#cmsPageSubtitle')?.value||'',blocks:$$('.cms-block-row',list).map(row=>({key:row.dataset.blockKey,visible:$('.cms-block-visible',row)?.checked!==false,title:$('.cms-block-title',row)?.value||''})),overrides}}
  function saveCurrentToCfg(){const c=ensureUi();c.ui.pages[activePageKey]=collectPageState();try{setDirty(true)}catch(e){}return c}
  async function persistCurrent(callSaveAll=true){try{saveCurrentToCfg();if(callSaveAll&&typeof saveAll==='function'){await saveAll()}else{StarroConfig.replace(getCfg());if(typeof cloudSession!=='undefined'&&cloudSession&&typeof saveRemote==='function')await saveRemote(getCfg())}toast('頁面設定已儲存');return true}catch(e){toast(e.message||String(e),true);return false}}
  function bindPageEvents(){
    $$('[data-cms-page]').forEach(b=>b.onclick=()=>{try{saveCurrentToCfg()}catch(e){}activePageKey=b.dataset.cmsPage;renderPageEditor();bindPageEvents()});
    const list=$('#cmsBlockList');if(list){let drag=null;$$('.cms-block-row',list).forEach(row=>{row.addEventListener('dragstart',()=>{drag=row;row.classList.add('dragging')});row.addEventListener('dragend',()=>{row.classList.remove('dragging');drag=null});row.addEventListener('dragover',e=>{e.preventDefault();if(!drag||drag===row)return;const r=row.getBoundingClientRect();if(e.clientY<r.top+r.height/2)list.insertBefore(drag,row);else list.insertBefore(drag,row.nextSibling)})});$$('[data-cms-up]',list).forEach(b=>b.onclick=()=>{const r=b.closest('.cms-block-row');if(r?.previousElementSibling)list.insertBefore(r,r.previousElementSibling)});$$('[data-cms-down]',list).forEach(b=>b.onclick=()=>{const r=b.closest('.cms-block-row');if(r?.nextElementSibling)list.insertBefore(r.nextElementSibling,r)})}
    $('#cmsResetBlocks')?.addEventListener('click',()=>{const c=ensureUi();delete c.ui.pages[activePageKey];renderPageEditor();bindPageEvents();toast('已恢復本頁預設，記得按儲存')});
    $('#cmsSavePage')?.addEventListener('click',()=>persistCurrent(true));
    $('#cmsSaveAllPages')?.addEventListener('click',()=>persistCurrent(true));
    $('#cmsExportPage')?.addEventListener('click',()=>{try{const obj=collectPageState();const a=document.createElement('a'),blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'});a.href=URL.createObjectURL(blob);a.download=`starro-page-${activePageKey}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}catch(e){toast(e.message,true)}});
  }
  function renderRawConfig(){const p=ensurePanel('rawConfig');if(!p)return;p.innerHTML=`<div class="panel-head"><div><h2>🧬 全站進階 JSON</h2><div class="muted">最底層的完整設定編輯器。現有功能、前台 UI、全部頁面設定都會在這份 JSON 裡。</div></div></div><div class="section"><div class="cms-raw-actions"><button class="btn primary" id="rawSave">套用並儲存</button><button class="btn ghost" id="rawRefresh">重新載入目前設定</button><button class="btn ghost" id="rawDownload">下載 JSON</button></div><textarea id="rawConfigJson" class="cms-json" style="min-height:620px">${esc(JSON.stringify(getCfg(),null,2))}</textarea></div>`}
  function bindRawEvents(){$('#rawRefresh')?.addEventListener('click',()=>{$('#rawConfigJson').value=JSON.stringify(getCfg(),null,2)});$('#rawDownload')?.addEventListener('click',()=>{const blob=new Blob([$('#rawConfigJson').value],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='starro-full-config.json';a.click()});$('#rawSave')?.addEventListener('click',async()=>{try{const obj=JSON.parse($('#rawConfigJson').value);cfg=deepMerge(StarroConfig.defaults,obj);StarroConfig.replace(cfg);if(typeof cloudSession!=='undefined'&&cloudSession&&typeof saveRemote==='function')await saveRemote(cfg);toast('全站 JSON 已套用並儲存');renderShell();openPanel('rawConfig')}catch(e){toast('JSON 錯誤：'+e.message,true)}})}
  function install(){insertNavButton('fullCms','🧩 全部頁面管理','homeConfig');insertNavButton('rawConfig','🧬 全站進階 JSON','syncCenter');insertFeatureRow('fullCms','🧩 全部頁面管理','8 個前台頁面：標題、區塊、排序、顯示、DOM 覆寫全部可管。','homeConfig');insertFeatureRow('rawConfig','🧬 全站進階 JSON','直接管理完整設定樹，作為最底層進階控制。','syncCenter');renderPageEditor();renderRawConfig();if(typeof bindOpen==='function')bindOpen();bindPageEvents();bindRawEvents();}
  function patch(){if(typeof renderShell==='function'&&!window.__starro_fullcms_render){const old=renderShell;renderShell=function(){const r=old.apply(this,arguments);install();return r};window.__starro_fullcms_render=true}if(typeof saveAll==='function'&&!window.__starro_fullcms_save){const old=saveAll;saveAll=async function(){try{if($('#cmsBlockList'))saveCurrentToCfg()}catch(e){}return old.apply(this,arguments)};window.__starro_fullcms_save=true}}
  function boot(){patch();if($('#adminApp')&&!$('#adminApp').classList.contains('hidden'))install()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
